# Inserts a blank line between shell prompts
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[helm]
disabled = false

# docker
[docker_context]
symbol = "🐋 "
disabled = false

# env variable
[env_var]
variable = "SHELL"
default = "unknown shell"
disabled = true

[git_status]
disabled = true
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
untracked = "🤷‍"
stashed = "📦"
modified = "📝"
staged.value = "++"
staged.style = "green"
#staged_count.enabled = true
#staged_count.style = "green"
renamed = "👅"
deleted = "🗑"

[gcloud]
disabled = true
format = '[($domain)(\($project\))]($style) '
#format = 'on [$symbol$account(@$domain)(\($project\))]($style) '


# kubernetes
[kubernetes]
symbol = "⛵ "
style = "green"
disabled = false
[kubernetes.context_aliases]

"gke_ignite-walker-project-geb_us-central1-a_primary-cluster" = "walker-ignite"

"gke_o-platform-gke-project_us-central1_central-cluster" = "walker-ops"
"gke_o-platform-gke-project_us-central1-a_central-cluster" = "walker-ops"

"gke_d-platform-gke-project_us-central1-a_central-cluster" = "walker-dev"
"gke_t-platform-gke-project_us-central1-a_central-cluster" = "walker-test"
"gke_s-platform-gke-project_us-central1-a_central-cluster" = "walker-stage"

"gke_p-platform-gke-project_us-central1-a_central-cluster" = "walker-prod"
"gke_p-platform-gke-project_us-central1_central-cluster" = "walker-prod"

"gke_dev-gke-project-gyj_us-central1-a_primary-cluster" = "remi-dev"
"gke_test-gke-project-yal_us-central1-a_primary-cluster" = "remi-test"
"gke_stage-gke-project_us-central1-a_primary-cluster" = "remi-stage"
"gke_prod-gke-project_us-central1-a_primary-cluster" = "remi-prod"

"gke_o-anthos-gke-project-pqm_us-central1_primary-cluster" = "anthos-ops"
"gke_d-anthos-gke-project-jem_us-central1_primary-cluster" = "anthos-dev"
"gke_t-anthos-gke-project-sqz_us-central1_primary-cluster" = "anthos-test"
"gke_s-anthos-gke-project-knt_us-central1_primary-cluster" = "anthos-stage"
"gke_p-anthos-gke-project-gej_us-central1_primary-cluster" = "anthos-prod"

"gke_o-argo-gke-project-qss_us-central1_primary-cluster" = "ops-argo"
"gke_d-argo-gke-project-dpo_us-central1_primary-cluster" = "dev-argo"
"gke_t-argo-gke-project-qss_us-central1_primary-cluster" = "test-argo"
"gke_s-argo-gke-project-qss_us-central1_primary-cluster" = "stage-argo"
"gke_p-argo-gke-project-qss_us-central1_primary-cluster" = "prod-argo"

[golang]
disabled = true

[terraform]
format = "[🏎💨 $workspace]($style) "
disabled = true

[python]
disabled = true

[nodejs]
disabled = true
